### ISSUE TITLE
Update to 1.20

### ISSUE THREAD

**Issue by calliecameron** [2ndDerivative/BabyDontHerdMe#6]
Ideally 1.20.1, since it's the most widely-used version.

**Comment by HoodBlah** [comment]
I second this!

**Comment by HoodBlah** [comment]
I tried updating myself using YouTube videos and chatgpt. I changing the version dependencies but got into an error with ID, player in one of the mixins. I tried a couple fixes and got it to run but the mechanics wouldn't work. The sheep weren't being lured and the wolf wouldn't respond to the whistle.

**Comment by 2ndDerivative** [comment]
I'll look into it :-)

**Comment by HoodBlah** [comment]
LET'S GOOOOOOOOOOOOOOOOO

**Comment by 2ndDerivative** [comment]
Done, should work now. Enjoy :>

**Comment by HoodBlah** [comment]
YEEEEEEEEAHHHHHHHHHHHHHHHHHHHHHHHHH
