### ISSUE TITLE
Forge 1.20.1 Sinytra Connector "this.container" is null 

### ISSUE THREAD

**Issue by HoodBlah** [2ndDerivative/BabyDontHerdMe#7]
Thank you for updating to 1.20.1! I tried running it on forge with Sinytra Connector it crashed on startup with this error

[debug.log](https://github.com/user-attachments/files/17625958/debug.log)
[latest.log](https://github.com/user-attachments/files/17625959/latest.log)

**Comment by 2ndDerivative** [comment]
you may be able to solve this by running Java 1.21, but I'll look into that sometime, though no guarantees

**Comment by 2ndDerivative** [comment]
Can you test this again in your setup with the 1.1.3 version? I removed the J21 dependency that was unnecessarily strict

**Comment by HoodBlah** [comment]
Everything works now! Thank you!
